/* tslint:disable */
/* eslint-disable */
/**
 * API de Géorisques
 * Description de l\'API de Géorisques
 *
 * The version of the OpenAPI document: 1.8.2a
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

